name: react-native-android-build-apk
on:
  push:
    branches:
      - main
      - develop
    pull_request:
    branches:
      - main
      - develop
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run coverage tests
        run: |
          npm run test:coverage
      - name: Prebuild
        run: |
          npx expo prebuild
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@9598b8a83feef37de07f549027fab50ecffe6a6e
        if: success() || failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.sources=src
            -Dsonar.tests=src/test
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info